name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Test .NET 5.0
      shell: pwsh
      run: dotnet test --logger:"console;verbosity=detailed" -c Release -f net5.0

  build:
    name: Push nuget packages if a new tag is pushed
    needs: test
    runs-on: ubuntu-latest
    env:
      ProjectName: Ve.DotNet
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      shell: pwsh
      run: dotnet build --no-restore -c Release
      
    - name: Push nuget packages
      shell: pwsh
      run: |
        dotnet nuget push ${{ env.ProjectName }}\bin\Release\*.nupkg -s https://nuget.pkg.github.com/luojunyuan -k ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
        dotnet nuget push ${{ env.ProjectName }}\bin\Release\*.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NuGetAPIKey }} --skip-duplicate

